baseURL = "https://infinitewalk.com/"
languageCode = "en-us"
title = "Infinite Walk"
theme = "coder" # set the theme
[taxonomies]
   tag = "tags"
   category = "categories"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params] # theme parameters
    author = "Umakant Jani" # author's name
    info = "Technology Magician" # author's job title or info
    description = "Umakant's personal website" # site description
    keywords = "blog,developer,personal" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = false
    hideCopyright = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Poetry"
    weight = 2
    url = "/poetry/"
